### ISSUE TITLE
npm i macaca-android --save failed

### ISSUE THREAD

**Issue by fannahlin** [macacajs/android-unicode#4]
npm i macaca-android --save failed

[Error: build failed]
D:\sogou\work\macacajs\macaca-test-sample\node_modules\macaca-android\node_modul
es\unlock-apk\script\build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (D:\sogou\work\macacajs\macaca-test-sample\node_
modules\macaca-android\node_modules\unlock-apk\node_modules\ant-build\lib\ant-bu
ild.js:100:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by xudafeng** [comment]
macaca doctor?

**Comment by xudafeng** [comment]
https://macacajs.github.io/macaca/faq.html

**Comment by fannahlin** [comment]
你给你链接并没有解决我的问题。
npm install macaca-android -g
安装失败。

[Error: build failed]
C:\Users\linshufang\AppData\Roaming\npm\node_modules\macaca-android\node_modules
\unlock-apk\script\build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (C:\Users\linshufang\AppData\Roaming\npm\node_mo
dules\macaca-android\node_modules\unlock-apk\node_modules\ant-build\lib\ant-buil
d.js:100:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

> macaca-chromedriver@1.0.17 install C:\Users\linshufang\AppData\Roaming\npm\nod
> e_modules\macaca-android\node_modules\macaca-chromedriver
> node ./bin/macaca-chromedriver install
> 
> > chromedriver cdn url: http://npm.taobao.org/mirrors/chromedriver/2.20/chromed
> > river_win32.zip
> > chromedriver local in C:\Users\linshufang\AppData\Roaming\npm\node_modules\ma
> > caca-android\node_modules\macaca-chromedriver\exec\chromedriver.exe

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "macaca-android" "-g"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! android-unicode@1.0.6 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the android-unicode@1.0.6 install script 'node ./script/build
.js'.
npm ERR! This is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sogou\work\macacajs\macaca-test-sample\npm-debug.log

**Comment by xudafeng** [comment]
sdk 什么版本

**Comment by fannahlin** [comment]
手机是4.2.2

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_45`
  ANDROID_HOME is set to `D:\sogou\adt-bundle-windows-x86-20140702\sdk`
  Platforms is set to `D:\adt-bundle-windows-x86-20140702\sdk\platforms\an
droid-8`
  Android tools is set to `D:\adt-bundle-windows-x86-20140702\sdk\tools\an
droid.bat`
  ADB tool is set to `D:\adt-bundle-windows-x86-20140702\sdk\platform-tool
s\adb.exe`
  ANT_HOME is set to `D:\adt-bundle-windows-x86-20140702\eclipse\plugins\o
rg.apache.ant_1.8.3.v201301120609`

  Installed driver list:

  electron: 1.1.2
  ios: 1.0.37

**Comment by fannahlin** [comment]
JAVA_HOME is set to C:\Program Files\Java\jdk1.8.0_45
[checkenv] Android SDK Tools Revision 25.1.7
[checkenv] Installed at D:\adt-bundle-windows-x86-20140702\sdk
[getbuildtools] Using latest Build Tools: 23.0.2

**Comment by xudafeng** [comment]
Android SDK Tools Revision 25.1.7 太高

**Comment by fannahlin** [comment]
**版本太高？那么我应该怎么做呢？** 

我运行macaca run -d macaca-mobile-sample.test.js时候，提示：>> please run: `npm install macaca-android -g`
然后，我运行npm install macaca-android -g， 就出现上边的错误。 这些版本是在运行npm install macaca-android -g时，看到屏幕上打印出来的日志。

**Comment by fannahlin** [comment]
npm i android-unicode -g 一样的错误， 根本就装不上这个

**Comment by sunyaLi** [comment]
我也遇到同样的问题，请问是怎么解决的？

**Comment by xudafeng** [comment]
https://macacajs.com/macaca/faq.html
